# Generated by Django 2.0.7 on 2018-07-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0002_dropoff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
